GOOGLE_API_KEY = "AIzaSyDljtEr0Z-UT81S_GqEEXBiX0c1ixd7YUE"
OPENAI_API_KEY = "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"
